#!/usr/bin/env bash

DATABASE=$1
USER=$2
PASSWORD=$3

mysql -uroot -e "CREATE USER '$USER'@'localhost' IDENTIFIED BY '$PASSWORD';"
mysql -uroot -e "CREATE SCHEMA $DATABASE;"
mysql -uroot -e "GRANT ALL PRIVILEGES ON $DATABASE.* TO '$USER'@'localhost';"
mysql -uroot -e "FLUSH PRIVILEGES;"

echo "Database created"
